[theme]
inherit = "bulma-basic"
stylesheets = ["style.css"]
sidebars = [
    "sidebar/logo.html",
    "sidebar/line.html",
    "sidebar/localtoc.html",
    "sidebar/globaltoc.html",
    "ablog/sidebar/summary.html",
    "sidebar/navigation.html",
]

[options]
bulma_version = "1.0.2"
bulmaswatch = ""
color_mode = ""
sidebar_position = "left"
navbar_icons = []
show_theme_credit = true
