version: '3'

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'
  SPHINX_DEFAULT_BUILD: 'dirhtml'
  SPHINX_SOURCE_DIR: 'contents'
  SPHINX_OUTPUT_DIR: 'build'
  SPHINX_OPTIONS: ''
  SPHINX_LANGUAGES:
    - 'ja'

env:
  SPHINXINTL_TRANSLATOR: "Kazuya Takei <myself@attakei.net>"

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - 'pnpm i'
      - 'lefthook install'
  dev:
    desc: 'Run docs server'
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - '{{.RUN_PYTHON}} sphinx-autobuild -b {{.SPHINX_DEFAULT_BUILD}} {{.SPHINX_SOURCE_DIR}} {{.SPHINX_OUTPUT_DIR}}/dirhtml'
  image:
    desc: 'Generate og image'
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - '{{.RUN_PYTHON}} gen-og-image --format=png contents/_static/images/og-image.png'
  build-*:
    desc: 'Make docs'
    dir: '{{.TASKFILE_DIR}}'
    vars:
      TARGET: '{{index .MATCH 0}}'
    cmds:
      - '{{.RUN_PYTHON}} sphinx-build -M {{.TARGET}} {{.SPHINX_SOURCE_DIR}} {{.SPHINX_OUTPUT_DIR}}'
  build:
    desc: 'Make docs (default target)'
    deps:
      - 'image'
      - 'build-{{.SPHINX_DEFAULT_BUILD}}'
  help:
    desc: 'Display help of docs'
    deps:
      - 'build-help'
  clean:
    desc: 'Clean build files of docs'
    deps:
      - 'build-clean'
    cmds:
      - 'rm -rf contents/_static/images/og-*'
