version: '3'

includes:
  docs:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.5.1'
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: '.'
      SPHINX_SOURCE_DIR: 'contents'
      SPHINX_OUTPUT_DIR: 'build'
      SPHINX_DEFAULT_BUILDER: 'dirhtml'
    flatten: true

vars:
  # If you run bare environment or activated venv, set '' (blank string)
  RUN_PYTHON: 'uv run'
  SPHINX_DEFAULT_BUILD: 'dirhtml'
  SPHINX_SOURCE_DIR: 'contents'
  SPHINX_OUTPUT_DIR: 'build'
  SPHINX_OPTIONS: ''
  SPHINX_LANGUAGES:
    - 'ja'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen --all-extras'
      - 'bun install'
      - 'lefthook install'
  textlint:
    desc: 'Run textlint'
    cmds:
      - '{{.RUN_PYTHON}} bun x textlint {{.CLI_ARGS}}'
    vars:
      RUN_PYTHON: 'uv run'
  image:
    desc: 'Generate og image'
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - '{{.RUN_PYTHON}} gen-og-image --format=png contents/_static/images/og-image.png'
    vars:
      RUN_PYTHON: 'uv run'
